image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - name: docker:23.0.1-dind
    alias: docker

before_script:
  - echo $CI_REGISTRY
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  tags:
    - shared
  script:
    - mkdir config
    - echo $CLIENT_CONFIG_JSON > config/app.json
    - docker build -f docker/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
